#!/usr/bin/env bash
set -e


if [[ $OSTYPE == "darwin"* || $OSTYPE == "FreeBSD" ]]; then
  PING_FLAGS="-c 1 `netstat -nr | grep 'default.*192' | gawk '{print $2}'`"
elif [[ $OSTYPE == "msys" ]]; then
  PING_FLAGS="-n 1 `ipconfig.exe | grep Gateway | gawk '{print $13}'`"
else
  PING_FLAGS="-c 1 `ip route show | grep -i 'default via'| gawk '{print $3 }'`"
fi


ping $PING_FLAGS > /dev/null 2>&1 && echo LAN\! && exit

echo Disconnected
exit 1
