#!/usr/bin/env bash
set -e
[[ -z $1 ]] && exit

function getExponentOf {
    number1=`numform $1`
    number2=`numform $2`
    echo $number1+$number2 | gawk -F+ '{ print $1^$2 }'
}

args="${*}"
args=($args)

result="$1"
for (( index = 1 ; index < ${#args[@]} ; ++index )) ; do
    result=`getExponentOf $result ${args[index]}`
done

echo $result