#!/usr/bin/env bash

brew install gawk coreutils tmux watch vim git tig bash-completion 

# krisp rectangle smudge/smudge/nightlight 
# screen slack discord tidal iterm2
# visual-studio-code intellij-idea-ce android-studio scrcpy
# qmk/qmk/qmk homebrew/cask-drivers/qmk-toolbox

defaults write com.apple.Dock showhidden -bool true
defaults write com.apple.Dock position-immutable -bool true
defaults write com.apple.Dock size-immutable -bool true
defaults write com.apple.Dock contents-immutable -bool false
defaults write com.apple.Dock autohide -bool true
defaults write com.apple.Dock scroll-to-open -bool true


defaults write com.apple.Finder AppleShowAllFiles true
defaults write com.apple.Finder _FXShowPosixPathInTitle -bool true
defaults write com.apple.Finder QuitMenuItem -bool true
defaults write com.apple.Finder CreateDesktop -bool false

killall Finder
killall Dock
