#!/usr/bin/env bash
set -e
quietly 'ls /Applications | grep "Xcode.app"' && echo 'Xcode already installed' && exit

[[ ! -z "$1" ]] && VERSION="$1" || VERSION='13.4.1'
surely "install Xcode $VERSION"
VERSION="Xcode_$VERSION"

cd "$HOME/Downloads"
curl -O "https://download.developer.apple.com/Developer_Tools/$VERSION/$VERSION.xip"

cd /Applications
APPARCHIVE="$HOME/Downloads/$VERSION.xip"
sudo xip -x "$APPARCHIVE"
rm "$APPARCHIVE"