#!/usr/bin/env bash
set -e

[[ ! -d "$1" ]] && echo 'provide valid directory' && exit 1
cd $1
JSONS=`ls *.json`
[[ -z "$JSONS" ]] && echo 'no jsons here' && exit 1

for JSON in $JSONS; do
    qmkbuild "$JSON"
done
